# Utiliser l'image officielle Nginx pour servir les fichiers statiques
FROM nginx:alpine

# Copier les fichiers frontend dans le répertoire de contenu Nginx
COPY . /usr/share/nginx/html

# Exposer le port HTTP
EXPOSE 80
