services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/app/data.json

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_data:
